docker-compose.yml
OVERVIEW.md
PLACEMENT_HUB_DOCUMENTATION.md
README.md
aws.txt
client/index.html
client/package.json
client/postcss.config.js
client/tailwind.config.js
client/vite.config.js
client/public/samples/bulk-users-template.csv
client/src/App.jsx
client/src/main.jsx
client/src/api/http.js
client/src/components/Badge.jsx
client/src/components/CodeEditor.jsx
client/src/components/EmptyState.jsx
client/src/components/Modal.jsx
client/src/components/PageHeader.jsx
client/src/components/ProtectedRoute.jsx
client/src/components/SectionCard.jsx
client/src/components/Skeleton.jsx
client/src/components/StatCard.jsx
client/src/context/AuthContext.jsx
client/src/context/ThemeContext.jsx
client/src/context/ToastContext.jsx
client/src/hooks/useAuth.js
client/src/hooks/useContestTimer.js
client/src/hooks/useTheme.js
client/src/hooks/useToast.js
client/src/layouts/AppShell.jsx
client/src/pages/AuthPage.jsx
client/src/styles/index.css
docker/client.Dockerfile
docker/server.Dockerfile
docker/runner/Dockerfile
server/debug_placement.js
server/package.json
server/test_api_updated.js
server/test_api.js
server/test_placement_api.js
server/test_quick.js
server/verify_seed.js
server/src/app.js
server/src/server.js
server/src/config/db.js
server/src/config/env.js
server/src/config/redis.js
server/src/constants/languages.js
server/src/constants/roles.js
server/src/controllers/adminController.js
server/src/controllers/authController.js
server/src/controllers/executionController.js
server/src/controllers/messageController.js
server/src/controllers/placementController.js
server/src/controllers/platformController.js
server/src/controllers/practiceSessionController.js
server/src/controllers/problemController.js
server/src/controllers/profileController.js
server/src/controllers/submissionController.js
server/src/controllers/teacherController.js
server/src/middleware/auth.js
server/src/middleware/errorHandler.js
server/src/middleware/rateLimit.js
server/src/middleware/validate.js
server/src/models/ActivityLog.js
server/src/models/ArchiveResource.js
server/src/models/Assignment.js
server/src/models/Bookmark.js
server/src/models/Company.js
server/src/models/Contest.js
server/src/models/DailyChallenge.js
server/src/models/Department.js
server/src/models/Message.js
server/src/models/MockTest.js
server/src/models/PracticeSession.js
server/src/models/Problem.js
server/src/models/ProfileMessage.js
server/src/models/Question.js
server/src/models/Submission.js
server/src/models/User.js
server/src/models/UserProgress.js
server/src/routes/adminProblemRoutes.js
server/src/routes/adminRoutes.js
server/src/routes/authRoutes.js
server/src/routes/contestRoutes.js
server/src/routes/executionRoutes.js
server/src/routes/index.js
server/src/routes/messageRoutes.js
server/src/routes/placementRoutes.js
server/src/routes/platformRoutes.js
server/src/routes/practiceSessionRoutes.js
server/src/routes/problemRoutes.js
